### PR TITLE
provide a cat command

### PR DESCRIPTION
**Pull request by rgbkrk**
I liked this terminal so much that I wanted to provide an extra command for fun.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Preview:

screen shot 2016-12-27 at 8 27 23 pm

**Comment by ladyleet** [comment]
@rgbkrk um, my new fave person? 😺

**Comment by jorgelainfiesta** [comment]
Awesome PR! thank you 🐱

**Comment by rgbkrk** [comment]
Excellent! 😹

**Pull request merged**
