### PR TITLE
add cat command to terminal window

### PR DESCRIPTION
**Pull request by ladyleet**
add cat command in help-command.hbs

### CODE REVIEW

**Comment by ladyleet** [comment]
@jorgelainfiesta woot woot woottttttt!!!!! 👍 ? 💯  :1st_place_medal:

**Comment by ladyleet** [comment]
@jorgelainfiesta i'm scared of pressing the merge button on our repos btw. so i never will.  <3

**Comment by ladyleet** [comment]
YAS

**Comment by jorgelainfiesta** [comment]
With the new cache in place, we now have to wait some time before we actually see the changes live. Taras is preparing something to fix that though.

**Pull request merged**
